(function(){'use strict';
var KEY='reflashWorkModeV1',state=load(),currentClientId=null,currentPropertyId=null;
function $(id){return document.getElementById(id)}function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{var s=localStorage.getItem(KEY);if(s)return JSON.parse(s)}catch(e){}return clone(WORK_DATA)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function show(id,title){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});$(id).classList.add('active');$('pageTitle').textContent=title||'Work Mode';document.querySelectorAll('.tab').forEach(function(t){t.classList.toggle('active',t.dataset.screen===id)});renderAll()}
function makeTask(text,category){return{id:'task-'+Date.now()+'-'+Math.random().toString(16).slice(2),text:text,done:false,category:category||'General'}}
function renderDaily(){$('dailyTasks').innerHTML=state.dailyTasks.length?state.dailyTasks.map(function(t){return'<div class="taskRow '+(t.done?'done':'')+'" data-task="'+t.id+'"><input type="checkbox" '+(t.done?'checked':'')+'><div class="taskText"><div>'+esc(t.text)+'</div><div class="taskCategory">'+esc(t.category)+'</div></div><button class="textButton deleteTask">Delete</button></div>'}).join(''):'<div class="empty">No tasks for today.</div>';document.querySelectorAll('[data-task]').forEach(function(r){r.querySelector('input').onchange=function(){var t=state.dailyTasks.find(function(x){return x.id===r.dataset.task});t.done=this.checked;save();renderDaily()};r.querySelector('.deleteTask').onclick=function(){state.dailyTasks=state.dailyTasks.filter(function(x){return x.id!==r.dataset.task});save();renderDaily()}})}
function clientCard(c){return'<div class="clientCard" data-client="'+c.id+'"><div class="cardIcon">👤</div><div class="grow"><strong>'+esc(c.name)+'</strong><div class="meta">'+esc(c.type)+' • '+esc(c.status)+'</div></div><div>›</div></div>'}
function renderClients(){var q=($('clientSearch').value||'').toLowerCase(),list=state.clients.filter(function(c){return!q||(c.name+' '+c.type+' '+c.status).toLowerCase().indexOf(q)!==-1});$('clientList').innerHTML=list.length?list.map(clientCard).join(''):'<div class="empty">No clients found.</div>';$('rentalClients').innerHTML=state.clients.filter(function(c){return c.type==='Rental'}).map(clientCard).join('')||'<div class="empty">No rental clients yet.</div>';$('salesClients').innerHTML=state.clients.filter(function(c){return c.type==='Residential Sale'}).map(clientCard).join('')||'<div class="empty">No residential sales clients yet.</div>';document.querySelectorAll('[data-client]').forEach(function(r){r.onclick=function(){openClient(r.dataset.client)}})}
function propertyCard(p){return'<div class="propertyCard" data-property="'+p.id+'"><div class="cardIcon">🏠</div><div class="grow"><strong>'+esc(p.address)+'</strong><div class="meta">'+esc(p.type)+' • '+esc(p.status)+'</div></div><div>›</div></div>'}
function renderProperties(){var q=($('propertySearch').value||'').toLowerCase(),list=state.properties.filter(function(p){return!q||(p.address+' '+p.type+' '+p.status).toLowerCase().indexOf(q)!==-1});$('propertyList').innerHTML=list.length?list.map(propertyCard).join(''):'<div class="empty">No properties found.</div>';document.querySelectorAll('[data-property]').forEach(function(r){r.onclick=function(){openProperty(r.dataset.property)}})}
function newClient(){var c={id:'client-'+Date.now(),name:'New Client',type:'Residential Sale',status:'Lead',phone:'',email:'',notes:'',tasks:[]};state.clients.unshift(c);save();openClient(c.id)}
function openClient(id){var c=state.clients.find(function(x){return x.id===id});if(!c)return;currentClientId=id;$('clientName').value=c.name;$('clientType').value=c.type;$('clientStatus').value=c.status;$('clientPhone').value=c.phone;$('clientEmail').value=c.email;$('clientNotes').value=c.notes;show('clientDetail',c.name)}
function saveClient(){var c=state.clients.find(function(x){return x.id===currentClientId});if(!c)return;c.name=$('clientName').value||'Untitled Client';c.type=$('clientType').value;c.status=$('clientStatus').value;c.phone=$('clientPhone').value;c.email=$('clientEmail').value;c.notes=$('clientNotes').value;save();show('clients','Clients')}
function deleteClient(){if(!currentClientId)return;if(confirm('Delete this client?')){state.clients=state.clients.filter(function(c){return c.id!==currentClientId});state.properties.forEach(function(p){if(p.clientId===currentClientId)p.clientId=''});save();show('clients','Clients')}}
function renderClientTasks(){var c=state.clients.find(function(x){return x.id===currentClientId});if(!c){$('clientTasks').innerHTML='';return}$('clientTasks').innerHTML=c.tasks.length?c.tasks.map(function(t){return'<div class="taskRow '+(t.done?'done':'')+'" data-client-task="'+t.id+'"><input type="checkbox" '+(t.done?'checked':'')+'><div class="taskText">'+esc(t.text)+'</div></div>'}).join(''):'<div class="empty">No client tasks.</div>';document.querySelectorAll('[data-client-task]').forEach(function(r){r.querySelector('input').onchange=function(){var t=c.tasks.find(function(x){return x.id===r.dataset.clientTask});t.done=this.checked;save();renderClientTasks()}})}
function defaultChecklist(){return['Verify listing status and showing instructions','Confirm appointment with client','Review taxes, property details, and disclosures','Arrive early and verify address','Observe exterior and neighborhood','Record buyer questions and feedback','Turn off lights and secure doors','Send follow-up and update notes'].map(function(t,i){return{id:'show-'+Date.now()+'-'+i,text:t,done:false}})}
function newProperty(){var p={id:'property-'+Date.now(),address:'New Property',type:'Residential Sale',status:'Research',clientId:'',notes:'',showingChecklist:defaultChecklist()};state.properties.unshift(p);save();openProperty(p.id)}
function openProperty(id){var p=state.properties.find(function(x){return x.id===id});if(!p)return;currentPropertyId=id;$('propertyAddress').value=p.address;$('propertyType').value=p.type;$('propertyStatus').value=p.status;$('propertyNotes').value=p.notes;$('propertyClient').innerHTML='<option value="">No client assigned</option>'+state.clients.map(function(c){return'<option value="'+c.id+'" '+(c.id===p.clientId?'selected':'')+'>'+esc(c.name)+'</option>'}).join('');show('propertyDetail',p.address)}
function saveProperty(){var p=state.properties.find(function(x){return x.id===currentPropertyId});if(!p)return;p.address=$('propertyAddress').value||'Untitled Property';p.type=$('propertyType').value;p.status=$('propertyStatus').value;p.clientId=$('propertyClient').value;p.notes=$('propertyNotes').value;save();show('properties','Properties')}
function deleteProperty(){if(!currentPropertyId)return;if(confirm('Delete this property?')){state.properties=state.properties.filter(function(p){return p.id!==currentPropertyId});save();show('properties','Properties')}}
function renderChecklist(){var p=state.properties.find(function(x){return x.id===currentPropertyId});if(!p){$('showingChecklist').innerHTML='';return}$('showingChecklist').innerHTML=p.showingChecklist.map(function(i){return'<label class="checklistItem '+(i.done?'done':'')+'" data-check="'+i.id+'"><input type="checkbox" '+(i.done?'checked':'')+'><span>'+esc(i.text)+'</span></label>'}).join('');document.querySelectorAll('[data-check]').forEach(function(r){r.querySelector('input').onchange=function(){var i=p.showingChecklist.find(function(x){return x.id===r.dataset.check});i.done=this.checked;save();renderChecklist()}})}
function renderAll(){renderDaily();renderClients();renderProperties();renderClientTasks();renderChecklist()}
document.querySelectorAll('.tab').forEach(function(t){t.onclick=function(){show(t.dataset.screen,t.querySelector('small').textContent)}});document.querySelectorAll('.modeCard').forEach(function(b){b.onclick=function(){show(b.dataset.mode,b.querySelector('strong').textContent)}});document.querySelectorAll('.backButton').forEach(function(b){b.onclick=function(){show(b.dataset.back,b.dataset.back==='clients'?'Clients':'Properties')}});
$('addButton').onclick=function(){show('addMenu','Create')};$('newTaskButton').onclick=function(){var t=prompt('New daily task');if(t){state.dailyTasks.unshift(makeTask(t,'General'));save();renderDaily()}};$('newClientButton').onclick=newClient;$('newPropertyButton').onclick=newProperty;$('clientSearch').oninput=renderClients;$('propertySearch').oninput=renderProperties;$('saveClient').onclick=saveClient;$('deleteClient').onclick=deleteClient;$('addClientTask').onclick=function(){var c=state.clients.find(function(x){return x.id===currentClientId}),t=prompt('New client task');if(c&&t){c.tasks.push(makeTask(t,'Client'));save();renderClientTasks()}};$('saveProperty').onclick=saveProperty;$('deleteProperty').onclick=deleteProperty;$('resetShowing').onclick=function(){var p=state.properties.find(function(x){return x.id===currentPropertyId});if(p){p.showingChecklist.forEach(function(i){i.done=false});save();renderChecklist()}};$('addMenuClient').onclick=newClient;$('addMenuProperty').onclick=newProperty;$('addMenuTask').onclick=function(){var t=prompt('New daily task');if(t){state.dailyTasks.unshift(makeTask(t,'General'));save();show('dashboard','Work Mode')}};renderAll();})();
if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){})})}