import type { ClientInput, ListingInput, SourceInput } from "./types";

export const seedSources: SourceInput[] = [
  {
    name: "NYC PLUTO",
    kind: "open",
    status: "ready",
    notes: "Tax-lot backbone, dataset 64uk-42ks. Enrich from NYC Open Data SODA; never a listing scrape.",
  },
  {
    name: "NYC ACRIS / DOF rolling sales",
    kind: "open",
    status: "ready",
    notes: "Comps, not live listings.",
  },
  {
    name: "OneKey MLS Grid",
    kind: "licensed",
    status: "blocked",
    notes: "Needs broker sponsor + RESO token.",
  },
  {
    name: "REBNY RLS",
    kind: "licensed",
    status: "blocked",
    notes: "Member firm feed.",
  },
  {
    name: "Manual paste / CSV",
    kind: "manual",
    status: "ready",
    notes: "Matrix export, FB/CL posts copied in.",
  },
  {
    name: "StreetEasy / Zillow / Craigslist / Maps",
    kind: "blocked",
    status: "never",
    notes: "No scrape.",
  },
];

export const seedBrokers: ClientInput[] = [
  {
    name: "David Schwartz",
    type: "broker",
    status: "active",
    company: "Compass",
    phone: "516-369-5464",
    email: "davidschwartz@compass.com",
    notes: "https://www.compass.com/agents/david-schwartz/",
  },
  {
    name: "Denise Bongiovanni",
    type: "broker",
    status: "active",
    company: "Compass",
    phone: "917-617-1867",
    email: "denise.bongiovanni@compass.com",
    notes: "https://www.compass.com/agents/denise-bongiovanni/",
  },
  {
    name: "Jane Wheatley",
    type: "broker",
    status: "active",
    company: "Corcoran",
    phone: "917-509-2025",
    email: "jane.wheatley@corcoran.com",
    notes: "https://www.corcoran.com/real-estate-agents/detail/agent/jane-wheatley/8043",
  },
  {
    name: "Ryan Lee",
    type: "broker",
    status: "active",
    company: "Corcoran SoHo",
    phone: "650-520-0770",
    email: "ryan.lee@corcoran.com",
    notes: "https://www.corcoran.com/real-estate-agents/detail/agent/ryan-lee/25196",
  },
  {
    name: "Justin Tuinstra",
    type: "broker",
    status: "active",
    company: "Elliman",
    phone: "917-535-3113",
    email: "jtuinstra@elliman.com",
    notes: "https://jtsellsnyc.com/rent/",
  },
  {
    name: "Honda Jayathilake",
    type: "broker",
    status: "active",
    company: "Elliman",
    phone: "646-639-0946",
    email: "Honda.Jayathilake@elliman.com",
    notes: "https://daniellelackorealestate.com/agents/honda-j",
  },
  {
    name: "Todd Buchanan",
    type: "broker",
    status: "active",
    company: "BHS",
    phone: "917-370-4820",
    email: "tbuchanan@bhsusa.com",
    notes: "https://www.bhsusa.com/real-estate-agent/todd-buchanan",
  },
  {
    name: "Colleen Breeckner",
    type: "broker",
    status: "active",
    company: "Nest Seekers",
    phone: "917-696-3571",
    email: "ColleenB@nestseekers.com",
    notes: "https://www.nestseekers.com/agent/colleen-breeckner/",
  },
  {
    name: "Crystal Rodriguez",
    type: "broker",
    status: "active",
    company: "Nest Seekers SoHo",
    phone: "646-228-3414",
    email: "CrystalR@nestseekers.com",
    notes: "https://www.nestseekers.com/agent/crystal-rodriguez/",
  },
  {
    name: "Michele Denby",
    type: "broker",
    status: "active",
    company: "Elliman FiDi",
    phone: "917-833-3310",
    email: "",
    notes: "",
  },
];

export const seedClients: ClientInput[] = [
  {
    name: "Maya Chen",
    phone: "917-555-0142",
    email: "maya.chen@example.com",
    budget_max: 3400,
    beds_min: 1,
    baths_min: 1,
    neighborhoods: ["Williamsburg", "Greenpoint"],
    pets: true,
    move_in_date: "2026-10-01",
    must_haves: ["dishwasher"],
    notes: "Cat, remote-first, wants sunlight and a quiet block.",
  },
  {
    name: "Jordan Hale",
    phone: "646-555-0198",
    email: "jordan.hale@example.com",
    budget_max: 5200,
    beds_min: 2,
    baths_min: 1,
    neighborhoods: ["Park Slope", "Carroll Gardens", "Prospect Heights"],
    pets: true,
    move_in_date: "2026-11-15",
    must_haves: ["laundry in unit"],
    notes: "Couple with a medium dog. Prefers near Prospect Park.",
  },
  {
    name: "Priya Shah",
    phone: "347-555-0110",
    email: "priya.shah@example.com",
    budget_max: 2900,
    beds_min: 0,
    baths_min: 1,
    neighborhoods: ["Astoria", "Long Island City"],
    pets: false,
    move_in_date: "2026-10-15",
    must_haves: ["doorman"],
    notes: "Studio or compact 1BR is fine. Commute to Midtown.",
  },
  {
    name: "Alex Rivera",
    phone: "212-555-0166",
    email: "alex.rivera@example.com",
    budget_max: 4500,
    beds_min: 2,
    baths_min: 1,
    neighborhoods: ["Harlem", "Upper West Side"],
    pets: true,
    move_in_date: "2026-09-30",
    must_haves: ["elevator"],
    notes: "Needs elevator. Weekend move-in preferred.",
  },
  {
    name: "Sam Okonkwo",
    phone: "929-555-0177",
    email: "sam.okonkwo@example.com",
    budget_max: 7000,
    beds_min: 3,
    baths_min: 2,
    neighborhoods: ["Bed-Stuy", "Downtown Brooklyn", "Fort Greene"],
    pets: true,
    move_in_date: "2026-12-01",
    must_haves: ["outdoor space"],
    notes: "Family of four. Backyard or terrace is the dream.",
  },
];

export const seedListings: ListingInput[] = [
  {
    source: "manual",
    external_id: "WB-184-3L",
    address: "184 N 8th Street #3L, Brooklyn, NY",
    neighborhood: "Williamsburg",
    beds: 1,
    baths: 1,
    price: 3200,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["dishwasher", "laundry in building", "hardwood"],
    notes: "Third-floor walk-up, south-facing.",
    pulled_at: "2026-09-12",
  },
  {
    source: "manual",
    external_id: "GP-88-2",
    address: "88 Guernsey Street #2, Brooklyn, NY",
    neighborhood: "Greenpoint",
    beds: 1,
    baths: 1,
    price: 3050,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["dishwasher", "outdoor space"],
    notes: "Private rear garden.",
    pulled_at: "2026-09-14",
  },
  {
    source: "manual",
    external_id: "WB-250-4A",
    address: "250 Bedford Avenue #4A, Brooklyn, NY",
    neighborhood: "Williamsburg",
    beds: 1,
    baths: 1,
    price: 3650,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["dishwasher", "doorman", "elevator"],
    notes: "Over Maya's $3,400 cap; keep for stretch conversations.",
    pulled_at: "2026-09-10",
  },
  {
    source: "manual",
    external_id: "LIC-4122-12B",
    address: "41-22 24th Street #12B, Queens, NY",
    neighborhood: "Long Island City",
    beds: 1,
    baths: 1,
    price: 3400,
    status: "available",
    url: "",
    pets_allowed: false,
    amenities: ["doorman", "elevator", "gym"],
    notes: "New construction, no pets.",
    pulled_at: "2026-09-16",
  },
  {
    source: "manual",
    external_id: "PS-12-2",
    address: "12 St Marks Avenue #2, Brooklyn, NY",
    neighborhood: "Park Slope",
    beds: 2,
    baths: 1,
    price: 4800,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["laundry in unit", "dishwasher"],
    notes: "Classic brownstone parlor floor.",
    pulled_at: "2026-09-11",
  },
  {
    source: "manual",
    external_id: "PS-445-3",
    address: "445 9th Street #3, Brooklyn, NY",
    neighborhood: "Park Slope",
    beds: 2,
    baths: 1.5,
    price: 5100,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["laundry in unit", "outdoor space", "dishwasher"],
    notes: "Garden access. Dogs ok with board approval.",
    pulled_at: "2026-09-13",
  },
  {
    source: "manual",
    external_id: "CG-88-5C",
    address: "88 3rd Place #5C, Brooklyn, NY",
    neighborhood: "Carroll Gardens",
    beds: 2,
    baths: 1,
    price: 4500,
    status: "available",
    url: "",
    pets_allowed: false,
    amenities: ["dishwasher", "laundry in building"],
    notes: "No pets. Great light.",
    pulled_at: "2026-09-09",
  },
  {
    source: "manual",
    external_id: "AS-3115-2R",
    address: "31-15 21st Avenue #2R, Queens, NY",
    neighborhood: "Astoria",
    beds: 1,
    baths: 1,
    price: 2600,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["laundry in building"],
    notes: "Walk-up, no doorman.",
    pulled_at: "2026-09-15",
  },
  {
    source: "manual",
    external_id: "LIC-2719-8F",
    address: "27-19 44th Drive #8F, Queens, NY",
    neighborhood: "Long Island City",
    beds: 0,
    baths: 1,
    price: 2750,
    status: "available",
    url: "",
    pets_allowed: false,
    amenities: ["doorman", "elevator", "gym"],
    notes: "Alcove studio.",
    pulled_at: "2026-09-17",
  },
  {
    source: "manual",
    external_id: "HA-201-4B",
    address: "201 W 109th Street #4B, New York, NY",
    neighborhood: "Harlem",
    beds: 2,
    baths: 1,
    price: 3900,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["elevator", "dishwasher"],
    notes: "Pre-war, cats and dogs.",
    pulled_at: "2026-09-08",
  },
  {
    source: "manual",
    external_id: "UWS-720-5D",
    address: "720 West End Avenue #5D, New York, NY",
    neighborhood: "Upper West Side",
    beds: 2,
    baths: 1,
    price: 4400,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["elevator", "doorman", "dishwasher"],
    notes: "Doorman building near the park.",
    pulled_at: "2026-09-07",
    borough: "Manhattan",
    bbl: "1012437505",
  },
  {
    source: "manual",
    external_id: "BS-88-1",
    address: "88 Hancock Street #1, Brooklyn, NY",
    neighborhood: "Bed-Stuy",
    beds: 3,
    baths: 2,
    price: 4200,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["outdoor space", "dishwasher"],
    notes: "Garden duplex.",
    pulled_at: "2026-09-06",
  },
  {
    source: "manual",
    external_id: "EV-150-3",
    address: "150 East 7th Street #3, New York, NY",
    neighborhood: "East Village",
    beds: 1,
    baths: 1,
    price: 3300,
    status: "available",
    url: "",
    pets_allowed: false,
    amenities: ["dishwasher"],
    notes: "Walk-up.",
    pulled_at: "2026-09-05",
  },
  {
    source: "manual",
    external_id: "WB-55-2L",
    address: "55 Berry Street #2L, Brooklyn, NY",
    neighborhood: "Williamsburg",
    beds: 2,
    baths: 1,
    price: 4900,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["dishwasher", "outdoor space"],
    notes: "Roof-deck share.",
    pulled_at: "2026-09-04",
  },
  {
    source: "manual",
    external_id: "DB-100-18K",
    address: "100 Willoughby Street #18K, Brooklyn, NY",
    neighborhood: "Downtown Brooklyn",
    beds: 3,
    baths: 2,
    price: 6500,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["doorman", "gym", "laundry in unit", "outdoor space"],
    notes: "High floor with terrace.",
    pulled_at: "2026-09-03",
    borough: "Brooklyn",
    bbl: "3001457502",
  },
  {
    source: "manual",
    external_id: "UWS-400-9A",
    address: "400 Central Park West #9A, New York, NY",
    neighborhood: "Upper West Side",
    beds: 3,
    baths: 2,
    price: 7800,
    status: "available",
    url: "",
    pets_allowed: false,
    amenities: ["doorman", "elevator", "gym"],
    notes: "Above Sam's budget and no pets.",
    pulled_at: "2026-09-02",
  },
  {
    source: "manual",
    external_id: "WB-22-3",
    address: "22 Skillman Avenue #3, Brooklyn, NY",
    neighborhood: "Williamsburg",
    beds: 0,
    baths: 1,
    price: 2400,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["laundry in building"],
    notes: "True studio. Too small for Maya's 1-bed minimum.",
    pulled_at: "2026-09-01",
  },
  {
    source: "manual",
    external_id: "PH-610-2",
    address: "610 Vanderbilt Avenue #2, Brooklyn, NY",
    neighborhood: "Prospect Heights",
    beds: 2,
    baths: 1,
    price: 4300,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["dishwasher", "laundry in unit"],
    notes: "Near the museum.",
    pulled_at: "2026-09-16",
  },
  {
    source: "manual",
    external_id: "WB-90-1A",
    address: "90 Wythe Avenue #1A, Brooklyn, NY",
    neighborhood: "Williamsburg",
    beds: 1,
    baths: 1,
    price: 3000,
    status: "rented",
    url: "",
    pets_allowed: true,
    amenities: ["dishwasher"],
    notes: "Already rented — should not appear in default match results.",
    pulled_at: "2026-08-20",
  },
  {
    source: "manual",
    external_id: "FG-40-4",
    address: "40 South Portland Avenue #4, Brooklyn, NY",
    neighborhood: "Fort Greene",
    beds: 3,
    baths: 2,
    price: 6200,
    status: "available",
    url: "",
    pets_allowed: true,
    amenities: ["outdoor space", "dishwasher", "laundry in building"],
    notes: "Brownstone with rear yard.",
    pulled_at: "2026-09-18",
  },
];
